//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmqpBrokerSpec) DeepCopyInto(out *AmqpBrokerSpec) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TlsSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmqpBrokerSpec.
func (in *AmqpBrokerSpec) DeepCopy() *AmqpBrokerSpec {
	if in == nil {
		return nil
	}
	out := new(AmqpBrokerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmqpSpec) DeepCopyInto(out *AmqpSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmqpSpec.
func (in *AmqpSpec) DeepCopy() *AmqpSpec {
	if in == nil {
		return nil
	}
	out := new(AmqpSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppConfigSpec) DeepCopyInto(out *AppConfigSpec) {
	*out = *in
	out.Quarkus = in.Quarkus
	out.EventGenerator = in.EventGenerator
	out.Amqp = in.Amqp
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppConfigSpec.
func (in *AppConfigSpec) DeepCopy() *AppConfigSpec {
	if in == nil {
		return nil
	}
	out := new(AppConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtemisAcceptorsSpec) DeepCopyInto(out *ArtemisAcceptorsSpec) {
	*out = *in
	in.Amqps.DeepCopyInto(&out.Amqps)
	in.Amqp.DeepCopyInto(&out.Amqp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtemisAcceptorsSpec.
func (in *ArtemisAcceptorsSpec) DeepCopy() *ArtemisAcceptorsSpec {
	if in == nil {
		return nil
	}
	out := new(ArtemisAcceptorsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtemisAmqpSpec) DeepCopyInto(out *ArtemisAmqpSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Expose != nil {
		in, out := &in.Expose, &out.Expose
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtemisAmqpSpec.
func (in *ArtemisAmqpSpec) DeepCopy() *ArtemisAmqpSpec {
	if in == nil {
		return nil
	}
	out := new(ArtemisAmqpSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtemisAmqpsSpec) DeepCopyInto(out *ArtemisAmqpsSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.VerifyHost != nil {
		in, out := &in.VerifyHost, &out.VerifyHost
		*out = new(bool)
		**out = **in
	}
	if in.Expose != nil {
		in, out := &in.Expose, &out.Expose
		*out = new(bool)
		**out = **in
	}
	if in.NeedClientAuth != nil {
		in, out := &in.NeedClientAuth, &out.NeedClientAuth
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtemisAmqpsSpec.
func (in *ArtemisAmqpsSpec) DeepCopy() *ArtemisAmqpsSpec {
	if in == nil {
		return nil
	}
	out := new(ArtemisAmqpsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtemisBrokerSpec) DeepCopyInto(out *ArtemisBrokerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtemisBrokerSpec.
func (in *ArtemisBrokerSpec) DeepCopy() *ArtemisBrokerSpec {
	if in == nil {
		return nil
	}
	out := new(ArtemisBrokerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtemisCertManagerSpec) DeepCopyInto(out *ArtemisCertManagerSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	out.IssuerRef = in.IssuerRef
	if in.DNSNames != nil {
		in, out := &in.DNSNames, &out.DNSNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtemisCertManagerSpec.
func (in *ArtemisCertManagerSpec) DeepCopy() *ArtemisCertManagerSpec {
	if in == nil {
		return nil
	}
	out := new(ArtemisCertManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtemisConsoleSpec) DeepCopyInto(out *ArtemisConsoleSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Expose != nil {
		in, out := &in.Expose, &out.Expose
		*out = new(bool)
		**out = **in
	}
	if in.SSLEnabled != nil {
		in, out := &in.SSLEnabled, &out.SSLEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtemisConsoleSpec.
func (in *ArtemisConsoleSpec) DeepCopy() *ArtemisConsoleSpec {
	if in == nil {
		return nil
	}
	out := new(ArtemisConsoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtemisCredentialsSpec) DeepCopyInto(out *ArtemisCredentialsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtemisCredentialsSpec.
func (in *ArtemisCredentialsSpec) DeepCopy() *ArtemisCredentialsSpec {
	if in == nil {
		return nil
	}
	out := new(ArtemisCredentialsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtemisJMXSpec) DeepCopyInto(out *ArtemisJMXSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtemisJMXSpec.
func (in *ArtemisJMXSpec) DeepCopy() *ArtemisJMXSpec {
	if in == nil {
		return nil
	}
	out := new(ArtemisJMXSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtemisOIDCSpec) DeepCopyInto(out *ArtemisOIDCSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtemisOIDCSpec.
func (in *ArtemisOIDCSpec) DeepCopy() *ArtemisOIDCSpec {
	if in == nil {
		return nil
	}
	out := new(ArtemisOIDCSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtemisPersistenceSpec) DeepCopyInto(out *ArtemisPersistenceSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.RequireLogin != nil {
		in, out := &in.RequireLogin, &out.RequireLogin
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtemisPersistenceSpec.
func (in *ArtemisPersistenceSpec) DeepCopy() *ArtemisPersistenceSpec {
	if in == nil {
		return nil
	}
	out := new(ArtemisPersistenceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtemisSpec) DeepCopyInto(out *ArtemisSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	out.Broker = in.Broker
	out.Credentials = in.Credentials
	in.Acceptors.DeepCopyInto(&out.Acceptors)
	in.Console.DeepCopyInto(&out.Console)
	in.Persistence.DeepCopyInto(&out.Persistence)
	if in.BrokerProperties != nil {
		in, out := &in.BrokerProperties, &out.BrokerProperties
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.CertManager.DeepCopyInto(&out.CertManager)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtemisSpec.
func (in *ArtemisSpec) DeepCopy() *ArtemisSpec {
	if in == nil {
		return nil
	}
	out := new(ArtemisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSpec) DeepCopyInto(out *CertManagerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSpec.
func (in *CertManagerSpec) DeepCopy() *CertManagerSpec {
	if in == nil {
		return nil
	}
	out := new(CertManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientConfigSpec) DeepCopyInto(out *ClientConfigSpec) {
	*out = *in
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]ProviderSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DnotamSubscriptions != nil {
		in, out := &in.DnotamSubscriptions, &out.DnotamSubscriptions
		*out = make([]DnotamSubscriptionSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Observability = in.Observability
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientConfigSpec.
func (in *ClientConfigSpec) DeepCopy() *ClientConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ClientConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientSpec) DeepCopyInto(out *ClientSpec) {
	*out = *in
	in.Mongo.DeepCopyInto(&out.Mongo)
	in.Config.DeepCopyInto(&out.Config)
	in.Resources.DeepCopyInto(&out.Resources)
	out.Probe = in.Probe
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientSpec.
func (in *ClientSpec) DeepCopy() *ClientSpec {
	if in == nil {
		return nil
	}
	out := new(ClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsumerValidatorMariaDBSpec) DeepCopyInto(out *ConsumerValidatorMariaDBSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsumerValidatorMariaDBSpec.
func (in *ConsumerValidatorMariaDBSpec) DeepCopy() *ConsumerValidatorMariaDBSpec {
	if in == nil {
		return nil
	}
	out := new(ConsumerValidatorMariaDBSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSpec) DeepCopyInto(out *DatabaseSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSpec.
func (in *DatabaseSpec) DeepCopy() *DatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnotamSubscriptionSpec) DeepCopyInto(out *DnotamSubscriptionSpec) {
	*out = *in
	if in.EventScenario != nil {
		in, out := &in.EventScenario, &out.EventScenario
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AirportHeliport != nil {
		in, out := &in.AirportHeliport, &out.AirportHeliport
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Airspace != nil {
		in, out := &in.Airspace, &out.Airspace
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnotamSubscriptionSpec.
func (in *DnotamSubscriptionSpec) DeepCopy() *DnotamSubscriptionSpec {
	if in == nil {
		return nil
	}
	out := new(DnotamSubscriptionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ed254ArtemisSpec) DeepCopyInto(out *Ed254ArtemisSpec) {
	*out = *in
	out.Storage = in.Storage
	out.Acceptors = in.Acceptors
	in.Console.DeepCopyInto(&out.Console)
	out.JMX = in.JMX
	if in.BrokerProperties != nil {
		in, out := &in.BrokerProperties, &out.BrokerProperties
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.OIDC = in.OIDC
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ed254ArtemisSpec.
func (in *Ed254ArtemisSpec) DeepCopy() *Ed254ArtemisSpec {
	if in == nil {
		return nil
	}
	out := new(Ed254ArtemisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ed254ConsumerAppSpec) DeepCopyInto(out *Ed254ConsumerAppSpec) {
	*out = *in
	in.Mongo.DeepCopyInto(&out.Mongo)
	in.Config.DeepCopyInto(&out.Config)
	in.Resources.DeepCopyInto(&out.Resources)
	out.Probe = in.Probe
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ed254ConsumerAppSpec.
func (in *Ed254ConsumerAppSpec) DeepCopy() *Ed254ConsumerAppSpec {
	if in == nil {
		return nil
	}
	out := new(Ed254ConsumerAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ed254ConsumerConfigSpec) DeepCopyInto(out *Ed254ConsumerConfigSpec) {
	*out = *in
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]ProviderSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Ed254Subscriptions != nil {
		in, out := &in.Ed254Subscriptions, &out.Ed254Subscriptions
		*out = make([]Ed254SubscriptionSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Observability = in.Observability
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ed254ConsumerConfigSpec.
func (in *Ed254ConsumerConfigSpec) DeepCopy() *Ed254ConsumerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(Ed254ConsumerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ed254DestinationAerodrome) DeepCopyInto(out *Ed254DestinationAerodrome) {
	*out = *in
	if in.AssignedArrivalRunway != nil {
		in, out := &in.AssignedArrivalRunway, &out.AssignedArrivalRunway
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ed254DestinationAerodrome.
func (in *Ed254DestinationAerodrome) DeepCopy() *Ed254DestinationAerodrome {
	if in == nil {
		return nil
	}
	out := new(Ed254DestinationAerodrome)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ed254FlightSelector) DeepCopyInto(out *Ed254FlightSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ed254FlightSelector.
func (in *Ed254FlightSelector) DeepCopy() *Ed254FlightSelector {
	if in == nil {
		return nil
	}
	out := new(Ed254FlightSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ed254MongoSpec) DeepCopyInto(out *Ed254MongoSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ed254MongoSpec.
func (in *Ed254MongoSpec) DeepCopy() *Ed254MongoSpec {
	if in == nil {
		return nil
	}
	out := new(Ed254MongoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ed254PostgresSpec) DeepCopyInto(out *Ed254PostgresSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ed254PostgresSpec.
func (in *Ed254PostgresSpec) DeepCopy() *Ed254PostgresSpec {
	if in == nil {
		return nil
	}
	out := new(Ed254PostgresSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ed254ProviderAppBaseSpec) DeepCopyInto(out *Ed254ProviderAppBaseSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	out.Observability = in.Observability
	out.OIDC = in.OIDC
	if in.Aerodromes != nil {
		in, out := &in.Aerodromes, &out.Aerodromes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ed254ProviderAppBaseSpec.
func (in *Ed254ProviderAppBaseSpec) DeepCopy() *Ed254ProviderAppBaseSpec {
	if in == nil {
		return nil
	}
	out := new(Ed254ProviderAppBaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ed254SubscriptionSpec) DeepCopyInto(out *Ed254SubscriptionSpec) {
	*out = *in
	if in.DestinationAerodrome != nil {
		in, out := &in.DestinationAerodrome, &out.DestinationAerodrome
		*out = make([]Ed254DestinationAerodrome, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PointName != nil {
		in, out := &in.PointName, &out.PointName
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FlightSelector != nil {
		in, out := &in.FlightSelector, &out.FlightSelector
		*out = make([]Ed254FlightSelector, len(*in))
		copy(*out, *in)
	}
	if in.SupplementaryData != nil {
		in, out := &in.SupplementaryData, &out.SupplementaryData
		*out = new(Ed254SupplementaryData)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ed254SubscriptionSpec.
func (in *Ed254SubscriptionSpec) DeepCopy() *Ed254SubscriptionSpec {
	if in == nil {
		return nil
	}
	out := new(Ed254SubscriptionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ed254SupplementaryData) DeepCopyInto(out *Ed254SupplementaryData) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ed254SupplementaryData.
func (in *Ed254SupplementaryData) DeepCopy() *Ed254SupplementaryData {
	if in == nil {
		return nil
	}
	out := new(Ed254SupplementaryData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventGeneratorSpec) DeepCopyInto(out *EventGeneratorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventGeneratorSpec.
func (in *EventGeneratorSpec) DeepCopy() *EventGeneratorSpec {
	if in == nil {
		return nil
	}
	out := new(EventGeneratorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalSpec) DeepCopyInto(out *GlobalSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalSpec.
func (in *GlobalSpec) DeepCopy() *GlobalSpec {
	if in == nil {
		return nil
	}
	out := new(GlobalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HPAConfig) DeepCopyInto(out *HPAConfig) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.TargetCPUUtilizationPercentage != nil {
		in, out := &in.TargetCPUUtilizationPercentage, &out.TargetCPUUtilizationPercentage
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HPAConfig.
func (in *HPAConfig) DeepCopy() *HPAConfig {
	if in == nil {
		return nil
	}
	out := new(HPAConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSpec.
func (in *ImageSpec) DeepCopy() *ImageSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressSpec) DeepCopyInto(out *IngressSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressSpec.
func (in *IngressSpec) DeepCopy() *IngressSpec {
	if in == nil {
		return nil
	}
	out := new(IngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IssuerRefSpec) DeepCopyInto(out *IssuerRefSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IssuerRefSpec.
func (in *IssuerRefSpec) DeepCopy() *IssuerRefSpec {
	if in == nil {
		return nil
	}
	out := new(IssuerRefSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaSpec) DeepCopyInto(out *KafkaSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaSpec.
func (in *KafkaSpec) DeepCopy() *KafkaSpec {
	if in == nil {
		return nil
	}
	out := new(KafkaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoSpec) DeepCopyInto(out *MongoSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoSpec.
func (in *MongoSpec) DeepCopy() *MongoSpec {
	if in == nil {
		return nil
	}
	out := new(MongoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservabilitySpec) DeepCopyInto(out *ObservabilitySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservabilitySpec.
func (in *ObservabilitySpec) DeepCopy() *ObservabilitySpec {
	if in == nil {
		return nil
	}
	out := new(ObservabilitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbeConfig) DeepCopyInto(out *ProbeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbeConfig.
func (in *ProbeConfig) DeepCopy() *ProbeConfig {
	if in == nil {
		return nil
	}
	out := new(ProbeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderAppBaseSpec) DeepCopyInto(out *ProviderAppBaseSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	out.Observability = in.Observability
	out.OIDC = in.OIDC
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderAppBaseSpec.
func (in *ProviderAppBaseSpec) DeepCopy() *ProviderAppBaseSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderAppBaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderArtemisAcceptorsSpec) DeepCopyInto(out *ProviderArtemisAcceptorsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderArtemisAcceptorsSpec.
func (in *ProviderArtemisAcceptorsSpec) DeepCopy() *ProviderArtemisAcceptorsSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderArtemisAcceptorsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderArtemisConsoleSpec) DeepCopyInto(out *ProviderArtemisConsoleSpec) {
	*out = *in
	if in.SSLEnabled != nil {
		in, out := &in.SSLEnabled, &out.SSLEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderArtemisConsoleSpec.
func (in *ProviderArtemisConsoleSpec) DeepCopy() *ProviderArtemisConsoleSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderArtemisConsoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderArtemisSpec) DeepCopyInto(out *ProviderArtemisSpec) {
	*out = *in
	out.Storage = in.Storage
	out.Acceptors = in.Acceptors
	in.Console.DeepCopyInto(&out.Console)
	out.JMX = in.JMX
	if in.BrokerProperties != nil {
		in, out := &in.BrokerProperties, &out.BrokerProperties
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.OIDC = in.OIDC
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderArtemisSpec.
func (in *ProviderArtemisSpec) DeepCopy() *ProviderArtemisSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderArtemisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderArtemisStorageSpec) DeepCopyInto(out *ProviderArtemisStorageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderArtemisStorageSpec.
func (in *ProviderArtemisStorageSpec) DeepCopy() *ProviderArtemisStorageSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderArtemisStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderOIDCSpec) DeepCopyInto(out *ProviderOIDCSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderOIDCSpec.
func (in *ProviderOIDCSpec) DeepCopy() *ProviderOIDCSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderOIDCSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderPostgresSpec) DeepCopyInto(out *ProviderPostgresSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderPostgresSpec.
func (in *ProviderPostgresSpec) DeepCopy() *ProviderPostgresSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderPostgresSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderSpec) DeepCopyInto(out *ProviderSpec) {
	*out = *in
	in.SubscriptionManager.DeepCopyInto(&out.SubscriptionManager)
	in.AmqpBroker.DeepCopyInto(&out.AmqpBroker)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderSpec.
func (in *ProviderSpec) DeepCopy() *ProviderSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderValidatorAMQPSpec) DeepCopyInto(out *ProviderValidatorAMQPSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderValidatorAMQPSpec.
func (in *ProviderValidatorAMQPSpec) DeepCopy() *ProviderValidatorAMQPSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderValidatorAMQPSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderValidatorBaseSpec) DeepCopyInto(out *ProviderValidatorBaseSpec) {
	*out = *in
	out.Keycloak = in.Keycloak
	out.MariaDB = in.MariaDB
	out.AMQP = in.AMQP
	out.MTLS = in.MTLS
	in.HPA.DeepCopyInto(&out.HPA)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderValidatorBaseSpec.
func (in *ProviderValidatorBaseSpec) DeepCopy() *ProviderValidatorBaseSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderValidatorBaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderValidatorKeycloakSpec) DeepCopyInto(out *ProviderValidatorKeycloakSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderValidatorKeycloakSpec.
func (in *ProviderValidatorKeycloakSpec) DeepCopy() *ProviderValidatorKeycloakSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderValidatorKeycloakSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderValidatorMTLSSpec) DeepCopyInto(out *ProviderValidatorMTLSSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderValidatorMTLSSpec.
func (in *ProviderValidatorMTLSSpec) DeepCopy() *ProviderValidatorMTLSSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderValidatorMTLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderValidatorMariaDBSpec) DeepCopyInto(out *ProviderValidatorMariaDBSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderValidatorMariaDBSpec.
func (in *ProviderValidatorMariaDBSpec) DeepCopy() *ProviderValidatorMariaDBSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderValidatorMariaDBSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuarkusSpec) DeepCopyInto(out *QuarkusSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuarkusSpec.
func (in *QuarkusSpec) DeepCopy() *QuarkusSpec {
	if in == nil {
		return nil
	}
	out := new(QuarkusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResilienceSpec) DeepCopyInto(out *ResilienceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResilienceSpec.
func (in *ResilienceSpec) DeepCopy() *ResilienceSpec {
	if in == nil {
		return nil
	}
	out := new(ResilienceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionManagerSpec) DeepCopyInto(out *SubscriptionManagerSpec) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TlsSpec)
		**out = **in
	}
	if in.Resilience != nil {
		in, out := &in.Resilience, &out.Resilience
		*out = new(ResilienceSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionManagerSpec.
func (in *SubscriptionManagerSpec) DeepCopy() *SubscriptionManagerSpec {
	if in == nil {
		return nil
	}
	out := new(SubscriptionManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimDigitalNotamConsumerSpec) DeepCopyInto(out *SwimDigitalNotamConsumerSpec) {
	*out = *in
	out.Global = in.Global
	out.CertManager = in.CertManager
	out.Kafka = in.Kafka
	in.Client.DeepCopyInto(&out.Client)
	in.HPA.DeepCopyInto(&out.HPA)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimDigitalNotamConsumerSpec.
func (in *SwimDigitalNotamConsumerSpec) DeepCopy() *SwimDigitalNotamConsumerSpec {
	if in == nil {
		return nil
	}
	out := new(SwimDigitalNotamConsumerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimDigitalNotamProviderBaseSpec) DeepCopyInto(out *SwimDigitalNotamProviderBaseSpec) {
	*out = *in
	out.Global = in.Global
	out.CertManager = in.CertManager
	in.Postgres.DeepCopyInto(&out.Postgres)
	in.Artemis.DeepCopyInto(&out.Artemis)
	out.Kafka = in.Kafka
	in.HPA.DeepCopyInto(&out.HPA)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimDigitalNotamProviderBaseSpec.
func (in *SwimDigitalNotamProviderBaseSpec) DeepCopy() *SwimDigitalNotamProviderBaseSpec {
	if in == nil {
		return nil
	}
	out := new(SwimDigitalNotamProviderBaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimDnotamConsumerValidatorSpec) DeepCopyInto(out *SwimDnotamConsumerValidatorSpec) {
	*out = *in
	if in.ReplicaCount != nil {
		in, out := &in.ReplicaCount, &out.ReplicaCount
		*out = new(int32)
		**out = **in
	}
	out.Global = in.Global
	out.AppConfig = in.AppConfig
	out.MariaDB = in.MariaDB
	in.Artemis.DeepCopyInto(&out.Artemis)
	out.CertManager = in.CertManager
	out.Image = in.Image
	in.HPA.DeepCopyInto(&out.HPA)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimDnotamConsumerValidatorSpec.
func (in *SwimDnotamConsumerValidatorSpec) DeepCopy() *SwimDnotamConsumerValidatorSpec {
	if in == nil {
		return nil
	}
	out := new(SwimDnotamConsumerValidatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimEd254ConsumerSpec) DeepCopyInto(out *SwimEd254ConsumerSpec) {
	*out = *in
	out.Global = in.Global
	out.CertManager = in.CertManager
	out.Kafka = in.Kafka
	in.Consumer.DeepCopyInto(&out.Consumer)
	in.HPA.DeepCopyInto(&out.HPA)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimEd254ConsumerSpec.
func (in *SwimEd254ConsumerSpec) DeepCopy() *SwimEd254ConsumerSpec {
	if in == nil {
		return nil
	}
	out := new(SwimEd254ConsumerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimEd254ConsumerValidatorSpec) DeepCopyInto(out *SwimEd254ConsumerValidatorSpec) {
	*out = *in
	if in.ReplicaCount != nil {
		in, out := &in.ReplicaCount, &out.ReplicaCount
		*out = new(int32)
		**out = **in
	}
	out.Global = in.Global
	out.AppConfig = in.AppConfig
	out.MariaDB = in.MariaDB
	in.Artemis.DeepCopyInto(&out.Artemis)
	out.CertManager = in.CertManager
	out.Image = in.Image
	in.HPA.DeepCopyInto(&out.HPA)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimEd254ConsumerValidatorSpec.
func (in *SwimEd254ConsumerValidatorSpec) DeepCopy() *SwimEd254ConsumerValidatorSpec {
	if in == nil {
		return nil
	}
	out := new(SwimEd254ConsumerValidatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimEd254ProviderBaseSpec) DeepCopyInto(out *SwimEd254ProviderBaseSpec) {
	*out = *in
	out.Global = in.Global
	out.CertManager = in.CertManager
	in.Postgres.DeepCopyInto(&out.Postgres)
	in.Artemis.DeepCopyInto(&out.Artemis)
	out.Kafka = in.Kafka
	in.HPA.DeepCopyInto(&out.HPA)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimEd254ProviderBaseSpec.
func (in *SwimEd254ProviderBaseSpec) DeepCopy() *SwimEd254ProviderBaseSpec {
	if in == nil {
		return nil
	}
	out := new(SwimEd254ProviderBaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimStatus) DeepCopyInto(out *SwimStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimStatus.
func (in *SwimStatus) DeepCopy() *SwimStatus {
	if in == nil {
		return nil
	}
	out := new(SwimStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TlsSpec) DeepCopyInto(out *TlsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TlsSpec.
func (in *TlsSpec) DeepCopy() *TlsSpec {
	if in == nil {
		return nil
	}
	out := new(TlsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FficeSubscriptionSpec) DeepCopyInto(out *FficeSubscriptionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FficeSubscriptionSpec.
func (in *FficeSubscriptionSpec) DeepCopy() *FficeSubscriptionSpec {
	if in == nil {
		return nil
	}
	out := new(FficeSubscriptionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FficeProviderAppBaseSpec) DeepCopyInto(out *FficeProviderAppBaseSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	out.Observability = in.Observability
	out.OIDC = in.OIDC
	if in.SwimTopics != nil {
		in, out := &in.SwimTopics, &out.SwimTopics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FficeProviderAppBaseSpec.
func (in *FficeProviderAppBaseSpec) DeepCopy() *FficeProviderAppBaseSpec {
	if in == nil {
		return nil
	}
	out := new(FficeProviderAppBaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FficeConsumerConfigSpec) DeepCopyInto(out *FficeConsumerConfigSpec) {
	*out = *in
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]ProviderSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FficeSubscriptions != nil {
		in, out := &in.FficeSubscriptions, &out.FficeSubscriptions
		*out = make([]FficeSubscriptionSpec, len(*in))
		copy(*out, *in)
	}
	out.Observability = in.Observability
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FficeConsumerConfigSpec.
func (in *FficeConsumerConfigSpec) DeepCopy() *FficeConsumerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(FficeConsumerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FficeConsumerAppSpec) DeepCopyInto(out *FficeConsumerAppSpec) {
	*out = *in
	in.Mongo.DeepCopyInto(&out.Mongo)
	in.Config.DeepCopyInto(&out.Config)
	in.Resources.DeepCopyInto(&out.Resources)
	out.Probe = in.Probe
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FficeConsumerAppSpec.
func (in *FficeConsumerAppSpec) DeepCopy() *FficeConsumerAppSpec {
	if in == nil {
		return nil
	}
	out := new(FficeConsumerAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimFficeConsumerSpec) DeepCopyInto(out *SwimFficeConsumerSpec) {
	*out = *in
	out.Global = in.Global
	out.CertManager = in.CertManager
	out.Kafka = in.Kafka
	in.Consumer.DeepCopyInto(&out.Consumer)
	in.HPA.DeepCopyInto(&out.HPA)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimFficeConsumerSpec.
func (in *SwimFficeConsumerSpec) DeepCopy() *SwimFficeConsumerSpec {
	if in == nil {
		return nil
	}
	out := new(SwimFficeConsumerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimFficeProviderBaseSpec) DeepCopyInto(out *SwimFficeProviderBaseSpec) {
	*out = *in
	out.Global = in.Global
	out.CertManager = in.CertManager
	in.Postgres.DeepCopyInto(&out.Postgres)
	in.Artemis.DeepCopyInto(&out.Artemis)
	out.Kafka = in.Kafka
	in.HPA.DeepCopyInto(&out.HPA)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimFficeProviderBaseSpec.
func (in *SwimFficeProviderBaseSpec) DeepCopy() *SwimFficeProviderBaseSpec {
	if in == nil {
		return nil
	}
	out := new(SwimFficeProviderBaseSpec)
	in.DeepCopyInto(out)
	return out
}
