kind: SwimDigitalNotamConsumer
apiVersion: apps.swim-developer.github.io/v1alpha1
metadata:
  name: swim-dnotam-consumer
spec:
  certManager:
    issuerKind: ClusterIssuer
    issuerName: swim-ca-issuer
  client:
    config:
      providers:
        - providerId: "provider"
          subscriptionManager:
            url: "https://dnotam-consumer-validator-swim-external-provider.apps.ocp4.masales.cloud"
          amqpBroker:
            host: "dnotam-consumer-validator-artemis-swim-external-provider.apps.ocp4.masales.cloud"
            port: 443
            sslEnabled: true
            username: "admin"
            password: "admin"
      dnotamSubscriptions:
        - topic: "DigitalNOTAMService"
          eventScenario:
            - "SFC.CON"
            - "AD.LIM"
          airportHeliport:
            - "EADH"
            - "EADD"
          description: "Surface contamination and aerodrome limitations"
          provider: "provider"
      observability:
        otelEndpoint: 'http://tempo-simplest-distributor.tempostack.svc.cluster.local:4317'
