apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: swim-openshift-operator
    app.kubernetes.io/managed-by: kustomize
  name: swimed254consumer-viewer-role
rules:
- apiGroups:
  - apps.swim-developer.github.io
  resources:
  - swimed254consumers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.swim-developer.github.io
  resources:
  - swimed254consumers/status
  verbs:
  - get
