sonar.projectKey=swim-operator
sonar.projectName=swim-operator

sonar.sources=.
sonar.exclusions=vendor/**,**/*_test.go,bundle/**,dist/**,hack/**,bin/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
