package cv

import (
	"fmt"
	"strings"

	commonapi "github.com/swim-developer/swim-operator-common/api/v1alpha1"
	"github.com/swim-developer/swim-operator-common/pkg/constants"
)

const (
	hdlsServiceClusterFQDNFmt = "%s-hdls-svc.%s.svc.cluster.local"
	apiHostSuffix             = "-api"
)

func CVBuildHosts(crName, ns, clusterDomain string) (artemisInternalHost, artemisIngressHost, appHost, appHTTPHost string) {
	artemisServiceName := fmt.Sprintf(constants.ArtemisSuffix, crName)
	appHost = fmt.Sprintf(constants.HostnameSuffix, crName, ns, clusterDomain)
	appHTTPHost = fmt.Sprintf("%s-http-%s.%s", crName, ns, clusterDomain)
	artemisIngressHost = fmt.Sprintf(constants.HostnameSuffix, artemisServiceName, ns, clusterDomain)
	artemisInternalHost = fmt.Sprintf(hdlsServiceClusterFQDNFmt, artemisServiceName, ns)
	return artemisInternalHost, artemisIngressHost, appHost, appHTTPHost
}

// cvArtemisIngressHost resolves the Artemis ingress hostname with the following priority:
// 1. p.Ingress.ArtemisHostOverride (explicit)
// 2. Derived from p.Ingress.HostOverride by replacing the first segment with the Artemis service name
// 3. fallback (auto-generated by CVBuildHosts)
func cvArtemisIngressHost(p CVBuildParams, fallback string) string {
	if p.Ingress.ArtemisHostOverride != "" {
		return p.Ingress.ArtemisHostOverride
	}
	if p.Ingress.HostOverride != "" {
		artemisServiceName := fmt.Sprintf(constants.ArtemisSuffix, p.CRName)
		if idx := strings.Index(p.Ingress.HostOverride, "."); idx != -1 {
			return artemisServiceName + p.Ingress.HostOverride[idx:]
		}
	}
	return fallback
}

// CVAPIIngressHost resolves the mTLS API ingress hostname with the following priority:
// 1. p.Ingress.APIHostOverride (explicit)
// 2. Derived from p.Ingress.HostOverride by appending "-api" to the CR name segment
// 3. Auto-generated from CR name and cluster domain
func CVAPIIngressHost(p CVBuildParams, clusterDomain string) string {
	if p.Ingress.APIHostOverride != "" {
		return p.Ingress.APIHostOverride
	}
	if p.Ingress.HostOverride != "" {
		apiName := p.CRName + apiHostSuffix
		if idx := strings.Index(p.Ingress.HostOverride, "."); idx != -1 {
			return apiName + p.Ingress.HostOverride[idx:]
		}
	}
	return fmt.Sprintf(constants.HostnameSuffix, p.CRName+apiHostSuffix, p.Namespace, clusterDomain)
}

func CVAmqpInternalHost(spec commonapi.SwimDnotamConsumerValidatorSpec, crName, ns string) string {
	if spec.Artemis.Enabled != nil && !*spec.Artemis.Enabled {
		bn := spec.Artemis.Broker.Name
		if bn == "" {
			bn = fmt.Sprintf(constants.ArtemisSuffix, crName)
		}
		return fmt.Sprintf(hdlsServiceClusterFQDNFmt, bn, ns)
	}
	return fmt.Sprintf(hdlsServiceClusterFQDNFmt, fmt.Sprintf(constants.ArtemisSuffix, crName), ns)
}
