apiVersion: apps.swim-developer.github.io/v1alpha1
kind: SwimDnotamConsumerValidator
metadata:
  name: swim-consumervalidator
  namespace: swim-consumervalidator
spec:
  certManager:
    issuerName: "swim-ca-issuer"
    issuerKind: "ClusterIssuer"
  artemis:
    broker:
      name: "swim-consumervalidator-artemis"
      size: 1
    credentials:
      adminUser: "admin"
      adminPassword: "adminPassword"
  appConfig:
    quarkus:
      httpPort: 8080
      sslPort: 8443
    amqp:
      port: 5672
      username: "admin"
      password: "adminPassword"
  mariadb:
    database: "consumervalidator"
    username: "consumervalidator"
    password: "consumervalidator123"
    port: 3306
    storageSize: "1Gi"
  image:
    repository: "quay.io/masales/swim-dnotam-consumer-validator"
    tag: "latest"

