//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ed254ProviderAppSpec) DeepCopyInto(out *Ed254ProviderAppSpec) {
	*out = *in
	in.Ed254ProviderAppBaseSpec.DeepCopyInto(&out.Ed254ProviderAppBaseSpec)
	out.Routes = in.Routes
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ed254ProviderAppSpec.
func (in *Ed254ProviderAppSpec) DeepCopy() *Ed254ProviderAppSpec {
	if in == nil {
		return nil
	}
	out := new(Ed254ProviderAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderAppSpec) DeepCopyInto(out *ProviderAppSpec) {
	*out = *in
	in.ProviderAppBaseSpec.DeepCopyInto(&out.ProviderAppBaseSpec)
	out.Routes = in.Routes
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderAppSpec.
func (in *ProviderAppSpec) DeepCopy() *ProviderAppSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderRoutesSpec) DeepCopyInto(out *ProviderRoutesSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderRoutesSpec.
func (in *ProviderRoutesSpec) DeepCopy() *ProviderRoutesSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderRoutesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderValidatorRouteSpec) DeepCopyInto(out *ProviderValidatorRouteSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderValidatorRouteSpec.
func (in *ProviderValidatorRouteSpec) DeepCopy() *ProviderValidatorRouteSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderValidatorRouteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderValidatorSpec) DeepCopyInto(out *ProviderValidatorSpec) {
	*out = *in
	in.ProviderValidatorBaseSpec.DeepCopyInto(&out.ProviderValidatorBaseSpec)
	out.Route = in.Route
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderValidatorSpec.
func (in *ProviderValidatorSpec) DeepCopy() *ProviderValidatorSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderValidatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimDigitalNotamConsumer) DeepCopyInto(out *SwimDigitalNotamConsumer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimDigitalNotamConsumer.
func (in *SwimDigitalNotamConsumer) DeepCopy() *SwimDigitalNotamConsumer {
	if in == nil {
		return nil
	}
	out := new(SwimDigitalNotamConsumer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwimDigitalNotamConsumer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimDigitalNotamConsumerList) DeepCopyInto(out *SwimDigitalNotamConsumerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwimDigitalNotamConsumer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimDigitalNotamConsumerList.
func (in *SwimDigitalNotamConsumerList) DeepCopy() *SwimDigitalNotamConsumerList {
	if in == nil {
		return nil
	}
	out := new(SwimDigitalNotamConsumerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwimDigitalNotamConsumerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimDigitalNotamProvider) DeepCopyInto(out *SwimDigitalNotamProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimDigitalNotamProvider.
func (in *SwimDigitalNotamProvider) DeepCopy() *SwimDigitalNotamProvider {
	if in == nil {
		return nil
	}
	out := new(SwimDigitalNotamProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwimDigitalNotamProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimDigitalNotamProviderList) DeepCopyInto(out *SwimDigitalNotamProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwimDigitalNotamProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimDigitalNotamProviderList.
func (in *SwimDigitalNotamProviderList) DeepCopy() *SwimDigitalNotamProviderList {
	if in == nil {
		return nil
	}
	out := new(SwimDigitalNotamProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwimDigitalNotamProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimDigitalNotamProviderSpec) DeepCopyInto(out *SwimDigitalNotamProviderSpec) {
	*out = *in
	in.SwimDigitalNotamProviderBaseSpec.DeepCopyInto(&out.SwimDigitalNotamProviderBaseSpec)
	in.Provider.DeepCopyInto(&out.Provider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimDigitalNotamProviderSpec.
func (in *SwimDigitalNotamProviderSpec) DeepCopy() *SwimDigitalNotamProviderSpec {
	if in == nil {
		return nil
	}
	out := new(SwimDigitalNotamProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimDnotamConsumerValidator) DeepCopyInto(out *SwimDnotamConsumerValidator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimDnotamConsumerValidator.
func (in *SwimDnotamConsumerValidator) DeepCopy() *SwimDnotamConsumerValidator {
	if in == nil {
		return nil
	}
	out := new(SwimDnotamConsumerValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwimDnotamConsumerValidator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimDnotamConsumerValidatorList) DeepCopyInto(out *SwimDnotamConsumerValidatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwimDnotamConsumerValidator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimDnotamConsumerValidatorList.
func (in *SwimDnotamConsumerValidatorList) DeepCopy() *SwimDnotamConsumerValidatorList {
	if in == nil {
		return nil
	}
	out := new(SwimDnotamConsumerValidatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwimDnotamConsumerValidatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimDnotamProviderValidator) DeepCopyInto(out *SwimDnotamProviderValidator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimDnotamProviderValidator.
func (in *SwimDnotamProviderValidator) DeepCopy() *SwimDnotamProviderValidator {
	if in == nil {
		return nil
	}
	out := new(SwimDnotamProviderValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwimDnotamProviderValidator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimDnotamProviderValidatorList) DeepCopyInto(out *SwimDnotamProviderValidatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwimDnotamProviderValidator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimDnotamProviderValidatorList.
func (in *SwimDnotamProviderValidatorList) DeepCopy() *SwimDnotamProviderValidatorList {
	if in == nil {
		return nil
	}
	out := new(SwimDnotamProviderValidatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwimDnotamProviderValidatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimEd254Consumer) DeepCopyInto(out *SwimEd254Consumer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimEd254Consumer.
func (in *SwimEd254Consumer) DeepCopy() *SwimEd254Consumer {
	if in == nil {
		return nil
	}
	out := new(SwimEd254Consumer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwimEd254Consumer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimEd254ConsumerList) DeepCopyInto(out *SwimEd254ConsumerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwimEd254Consumer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimEd254ConsumerList.
func (in *SwimEd254ConsumerList) DeepCopy() *SwimEd254ConsumerList {
	if in == nil {
		return nil
	}
	out := new(SwimEd254ConsumerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwimEd254ConsumerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimEd254ConsumerValidator) DeepCopyInto(out *SwimEd254ConsumerValidator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimEd254ConsumerValidator.
func (in *SwimEd254ConsumerValidator) DeepCopy() *SwimEd254ConsumerValidator {
	if in == nil {
		return nil
	}
	out := new(SwimEd254ConsumerValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwimEd254ConsumerValidator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimEd254ConsumerValidatorList) DeepCopyInto(out *SwimEd254ConsumerValidatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwimEd254ConsumerValidator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimEd254ConsumerValidatorList.
func (in *SwimEd254ConsumerValidatorList) DeepCopy() *SwimEd254ConsumerValidatorList {
	if in == nil {
		return nil
	}
	out := new(SwimEd254ConsumerValidatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwimEd254ConsumerValidatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimEd254Provider) DeepCopyInto(out *SwimEd254Provider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimEd254Provider.
func (in *SwimEd254Provider) DeepCopy() *SwimEd254Provider {
	if in == nil {
		return nil
	}
	out := new(SwimEd254Provider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwimEd254Provider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimEd254ProviderList) DeepCopyInto(out *SwimEd254ProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwimEd254Provider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimEd254ProviderList.
func (in *SwimEd254ProviderList) DeepCopy() *SwimEd254ProviderList {
	if in == nil {
		return nil
	}
	out := new(SwimEd254ProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwimEd254ProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimEd254ProviderSpec) DeepCopyInto(out *SwimEd254ProviderSpec) {
	*out = *in
	in.SwimEd254ProviderBaseSpec.DeepCopyInto(&out.SwimEd254ProviderBaseSpec)
	in.Provider.DeepCopyInto(&out.Provider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimEd254ProviderSpec.
func (in *SwimEd254ProviderSpec) DeepCopy() *SwimEd254ProviderSpec {
	if in == nil {
		return nil
	}
	out := new(SwimEd254ProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimEd254ProviderValidator) DeepCopyInto(out *SwimEd254ProviderValidator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimEd254ProviderValidator.
func (in *SwimEd254ProviderValidator) DeepCopy() *SwimEd254ProviderValidator {
	if in == nil {
		return nil
	}
	out := new(SwimEd254ProviderValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwimEd254ProviderValidator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimEd254ProviderValidatorList) DeepCopyInto(out *SwimEd254ProviderValidatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwimEd254ProviderValidator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimEd254ProviderValidatorList.
func (in *SwimEd254ProviderValidatorList) DeepCopy() *SwimEd254ProviderValidatorList {
	if in == nil {
		return nil
	}
	out := new(SwimEd254ProviderValidatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwimEd254ProviderValidatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FficeProviderAppSpec) DeepCopyInto(out *FficeProviderAppSpec) {
	*out = *in
	in.FficeProviderAppBaseSpec.DeepCopyInto(&out.FficeProviderAppBaseSpec)
	out.Routes = in.Routes
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FficeProviderAppSpec.
func (in *FficeProviderAppSpec) DeepCopy() *FficeProviderAppSpec {
	if in == nil {
		return nil
	}
	out := new(FficeProviderAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimFficeConsumer) DeepCopyInto(out *SwimFficeConsumer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimFficeConsumer.
func (in *SwimFficeConsumer) DeepCopy() *SwimFficeConsumer {
	if in == nil {
		return nil
	}
	out := new(SwimFficeConsumer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwimFficeConsumer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimFficeConsumerList) DeepCopyInto(out *SwimFficeConsumerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwimFficeConsumer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimFficeConsumerList.
func (in *SwimFficeConsumerList) DeepCopy() *SwimFficeConsumerList {
	if in == nil {
		return nil
	}
	out := new(SwimFficeConsumerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwimFficeConsumerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimFficeConsumerValidator) DeepCopyInto(out *SwimFficeConsumerValidator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimFficeConsumerValidator.
func (in *SwimFficeConsumerValidator) DeepCopy() *SwimFficeConsumerValidator {
	if in == nil {
		return nil
	}
	out := new(SwimFficeConsumerValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwimFficeConsumerValidator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimFficeConsumerValidatorList) DeepCopyInto(out *SwimFficeConsumerValidatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwimFficeConsumerValidator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimFficeConsumerValidatorList.
func (in *SwimFficeConsumerValidatorList) DeepCopy() *SwimFficeConsumerValidatorList {
	if in == nil {
		return nil
	}
	out := new(SwimFficeConsumerValidatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwimFficeConsumerValidatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimFficeProvider) DeepCopyInto(out *SwimFficeProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimFficeProvider.
func (in *SwimFficeProvider) DeepCopy() *SwimFficeProvider {
	if in == nil {
		return nil
	}
	out := new(SwimFficeProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwimFficeProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimFficeProviderList) DeepCopyInto(out *SwimFficeProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwimFficeProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimFficeProviderList.
func (in *SwimFficeProviderList) DeepCopy() *SwimFficeProviderList {
	if in == nil {
		return nil
	}
	out := new(SwimFficeProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwimFficeProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimFficeProviderSpec) DeepCopyInto(out *SwimFficeProviderSpec) {
	*out = *in
	in.SwimFficeProviderBaseSpec.DeepCopyInto(&out.SwimFficeProviderBaseSpec)
	in.Provider.DeepCopyInto(&out.Provider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimFficeProviderSpec.
func (in *SwimFficeProviderSpec) DeepCopy() *SwimFficeProviderSpec {
	if in == nil {
		return nil
	}
	out := new(SwimFficeProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimFficeProviderValidator) DeepCopyInto(out *SwimFficeProviderValidator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimFficeProviderValidator.
func (in *SwimFficeProviderValidator) DeepCopy() *SwimFficeProviderValidator {
	if in == nil {
		return nil
	}
	out := new(SwimFficeProviderValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwimFficeProviderValidator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwimFficeProviderValidatorList) DeepCopyInto(out *SwimFficeProviderValidatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwimFficeProviderValidator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwimFficeProviderValidatorList.
func (in *SwimFficeProviderValidatorList) DeepCopy() *SwimFficeProviderValidatorList {
	if in == nil {
		return nil
	}
	out := new(SwimFficeProviderValidatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwimFficeProviderValidatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
