# This rule is not used by the project swim-kubernetes-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over apps.swim-developer.github.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: swim-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
  name: swimdigitalnotamconsumer-admin-role
rules:
- apiGroups:
  - apps.swim-developer.github.io
  resources:
  - swimdigitalnotamconsumers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.swim-developer.github.io
  resources:
  - swimdigitalnotamconsumers/status
  verbs:
  - get
