apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: swim-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
  name: swimfficeprovidervalidator-admin-role
rules:
- apiGroups:
  - apps.swim-developer.github.io
  resources:
  - swimfficeprovidervalidators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.swim-developer.github.io
  resources:
  - swimfficeprovidervalidators/status
  verbs:
  - get
