apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "swim-kubernetes-operator.serviceAccountName" . }}
  labels:
    {{- include "swim-kubernetes-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "swim-kubernetes-operator.fullname" . }}-manager-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "persistentvolumeclaims", "secrets", "serviceaccounts", "services"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["apps.swim-developer.github.io"]
  resources: ["swimdigitalnotamconsumers", "swimdigitalnotamproviders", "swimdnotamprovidervalidators", "swimdnotamconsumervalidators"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["apps.swim-developer.github.io"]
  resources: ["swimdigitalnotamconsumers/finalizers", "swimdigitalnotamproviders/finalizers", "swimdnotamprovidervalidators/finalizers", "swimdnotamconsumervalidators/finalizers"]
  verbs: ["update"]
- apiGroups: ["apps.swim-developer.github.io"]
  resources: ["swimdigitalnotamconsumers/status", "swimdigitalnotamproviders/status", "swimdnotamprovidervalidators/status", "swimdnotamconsumervalidators/status"]
  verbs: ["get", "patch", "update"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["broker.amq.io"]
  resources: ["activemqartemises"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["cert-manager.io"]
  resources: ["certificates"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["kafka.strimzi.io"]
  resources: ["kafkanodepools", "kafkas", "kafkatopics"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingressclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["rolebindings", "roles"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["console.streamshub.github.com"]
  resources: ["consoles"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
- apiGroups: ["authorization.k8s.io"]
  resources: ["subjectaccessreviews"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "swim-kubernetes-operator.fullname" . }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "swim-kubernetes-operator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "swim-kubernetes-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.leaderElection.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "swim-kubernetes-operator.fullname" . }}-leader-election-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "swim-kubernetes-operator.fullname" . }}-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "swim-kubernetes-operator.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "swim-kubernetes-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
