apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- apps_v1alpha1_swimdigitalnotamconsumer.yaml
- apps_v1alpha1_swimdigitalnotamprovider.yaml
- apps_v1alpha1_swimdnotamconsumervalidator.yaml
- apps_v1alpha1_swimdnotamprovidervalidator.yaml
- apps_v1alpha1_swimed254consumer.yaml
- apps_v1alpha1_swimed254provider.yaml
- apps_v1alpha1_swimed254consumervalidator.yaml
- apps_v1alpha1_swimed254providervalidator.yaml
- apps_v1alpha1_swimfficeconsumer.yaml
- apps_v1alpha1_swimfficeprovider.yaml
- apps_v1alpha1_swimfficeconsumervalidator.yaml
- apps_v1alpha1_swimfficeprovidervalidator.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
